import { Link, useParams } from 'react-router-dom'

type Policy={title:string;updated:string;sections:Array<[string,string]>}
const policies:Record<string,Policy>={
  privacy:{title:'Privacy policy',updated:'10 September 2026',sections:[['What we collect','Job Radar collects only the account details, career preferences, CV/resume files, resume text you provide, saved/application activity, and generated application documents needed to provide the service.'],['How we use it','We use this information to authenticate you, match jobs, store your application progress, and generate documents you request. We do not sell personal data.'],['AI processing','If an AI provider is configured and you request generation, relevant CV and job text may be sent to that provider for the requested draft. The current OpenAI integration is configured not to store Responses API output state. Without an AI key, Job Radar uses a local structured fallback.'],['Storage and access','Resumes are stored in a private Supabase bucket. Database row-level security restricts user-owned records to the authenticated owner.'],['Your choices','You can replace your CV, edit resume text, delete generated documents, or stop using the service. Account-deletion tooling should be added before any public commercial launch.'],['Local compliance','This project is designed around data-minimization and consent principles. Deployment owners remain responsible for reviewing applicable privacy, employment, consumer, and data-protection law in every jurisdiction where they operate.']]},
  terms:{title:'Terms of use',updated:'10 September 2026',sections:[['Purpose','Job Radar helps users discover jobs and prepare applications. It does not guarantee interviews, offers, salary, eligibility, or hiring outcomes.'],['Job listings','Listings are aggregated from supported public feeds or official application destinations. Employers and source platforms control the underlying job information. Users should verify deadlines and requirements at the original source before applying.'],['Application documents','Generated resumes and cover letters are drafts. Users must review them before submission. Job Radar is designed not to invent credentials, but users remain responsible for the accuracy of submitted materials.'],['Acceptable use','Do not use Job Radar to misrepresent qualifications, automate abusive applications, scrape restricted platforms, or violate third-party terms.'],['Service changes','Sources and features may change as public APIs, platform permissions, and provider availability change.']]},
  cookies:{title:'Cookies and local storage',updated:'10 September 2026',sections:[['Current use','Job Radar currently does not use advertising or analytics cookies. Supabase authentication may use browser storage needed to keep you signed in, and Job Radar stores a local acknowledgement of this notice.'],['Third parties','The app intentionally avoids third-party advertising pixels and social embeds. External job links open the original source in a new tab.'],['Future tracking','If optional analytics or marketing tracking is added later, it should remain disabled until the user has been given the consent controls required by applicable law.']]},
  accessibility:{title:'Accessibility statement',updated:'10 September 2026',sections:[['Commitment','Job Radar aims to be usable with a keyboard, screen reader, zoom, and high-contrast display settings.'],['What we check','Controls use visible labels, focus states, semantic headings, keyboard-accessible links and buttons, and text/background combinations selected for readable contrast. Decorative icons do not carry essential meaning by themselves.'],['Images','The current product UI does not rely on content images. If meaningful images are added later, they must include useful alternative text; decorative images should use empty alt text.'],['Known limitations','Accessibility should be retested after major visual changes and before a public production launch.']]},
  refunds:{title:'Refund policy',updated:'10 September 2026',sections:[['No paid plan currently','Job Radar does not currently sell subscriptions, credits, or other paid products, so there are no customer payments to refund.'],['If payments are introduced','Before accepting payment, the operator should publish pricing, cancellation, refund eligibility, billing contact information, and any legally required cooling-off or consumer rights for the relevant market.']]},
}

export default function PolicyPage(){const{slug='privacy'}=useParams();const policy=policies[slug]??policies.privacy;return <main className="policyPage"><a className="skipLink" href="#policy">Skip to content</a><div className="policyTop"><Link to="/" className="publicBrand"><span className="brandMark">J</span><b>Job Radar</b></Link><Link className="btn secondary" to="/">Back home</Link></div><article id="policy"><p className="eyebrow">POLICY</p><h1>{policy.title}</h1><p className="muted">Last updated {policy.updated}</p>{policy.sections.map(([title,body])=><section key={title}><h2>{title}</h2><p>{body}</p></section>)}</article></main>}
