import {useEffect,useMemo,useState} from 'react'
import {Download,FilePenLine,Sparkles,Upload} from 'lucide-react'
import {supabase} from '../services/supabase'
import {useAuth} from '../hooks/useAuth'

type Resume={id:string;original_filename:string;storage_path:string;content_type:string;extracted_text:string|null}
type MatchJob={job_id:string;fit_score:number;jobs:{id:string;title:string;company:string}|null}
type DocumentMode='resume'|'cover_letter'

export default function ResumePage(){
  const{user}=useAuth();const[resume,setResume]=useState<Resume|null>(null);const[sourceText,setSourceText]=useState('');const[file,setFile]=useState<File|null>(null);const[jobs,setJobs]=useState<MatchJob[]>([]);const[selectedJobId,setSelectedJobId]=useState('');const[mode,setMode]=useState<DocumentMode>('resume');const[instructions,setInstructions]=useState('');const[output,setOutput]=useState('');const[generationMode,setGenerationMode]=useState('');const[status,setStatus]=useState('');const[busy,setBusy]=useState(false)
  const selectedJob=useMemo(()=>jobs.find(j=>j.job_id===selectedJobId)?.jobs??null,[jobs,selectedJobId])

  async function loadResume(){if(!user)return;const{data,error}=await supabase.from('user_resumes').select('id,original_filename,storage_path,content_type,extracted_text').eq('user_id',user.id).eq('is_primary',true).maybeSingle();if(error){setStatus(error.message);return}const next=data as Resume|null;setResume(next);setSourceText(next?.extracted_text??'')}
  async function loadJobs(){if(!user)return;const{data,error}=await supabase.from('user_job_matches').select('job_id,fit_score,jobs(id,title,company)').eq('user_id',user.id).order('fit_score',{ascending:false}).limit(60);if(error){setStatus(error.message);return}const next=(data??[]) as unknown as MatchJob[];setJobs(next);if(!selectedJobId&&next[0])setSelectedJobId(next[0].job_id)}
  useEffect(()=>{void loadResume();void loadJobs()},[user])
  useEffect(()=>{if(!user||!selectedJobId)return;setOutput('');const table=mode==='resume'?'tailored_resumes':'cover_letters';const select=mode==='resume'?'content,generation_mode':'content,generation_mode';supabase.from(table).select(select).eq('user_id',user.id).eq('job_id',selectedJobId).maybeSingle().then(({data})=>{const row=data as {content?:string;generation_mode?:string}|null;setOutput(row?.content??'');setGenerationMode(row?.generation_mode??'')})},[user,selectedJobId,mode])

  async function replaceResume(){if(!user||!file)return;setBusy(true);setStatus('Uploading and reading your CV…');const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'_');const path=`${user.id}/${crypto.randomUUID()}-${safe}`;try{const{error:uploadError}=await supabase.storage.from('resumes').upload(path,file,{contentType:file.type||'application/octet-stream'});if(uploadError)throw uploadError;if(resume){const{error}=await supabase.from('user_resumes').update({is_primary:false,updated_at:new Date().toISOString()}).eq('id',resume.id).eq('user_id',user.id);if(error)throw error}const{data:newResume,error:insertError}=await supabase.from('user_resumes').insert({user_id:user.id,original_filename:file.name,storage_path:path,content_type:file.type||'application/octet-stream',is_primary:true}).select('id').single();if(insertError){if(resume)await supabase.from('user_resumes').update({is_primary:true}).eq('id',resume.id).eq('user_id',user.id);throw insertError}const{data:parseData,error:parseError}=await supabase.functions.invoke('parse-resume',{body:{resumeId:newResume.id}});if(parseError)setStatus(`Uploaded. Automatic text extraction needs review: ${parseError.message}`);else if(parseData?.parsed)setStatus('CV updated and text extracted. Review the text below before generating documents.');else setStatus(`CV updated. ${parseData?.reason??'Paste or edit the source text below.'}`);setFile(null);await loadResume()}catch(error){setStatus(error instanceof Error?error.message:'Could not replace resume')}finally{setBusy(false)}}
  async function saveSource(){if(!user||!resume)return;setBusy(true);setStatus('Saving source resume…');const{error}=await supabase.from('user_resumes').update({extracted_text:sourceText.trim(),updated_at:new Date().toISOString()}).eq('id',resume.id).eq('user_id',user.id);setStatus(error?error.message:'Source resume saved.');setBusy(false)}
  async function generate(nextMode:DocumentMode){if(!selectedJobId){setStatus('Choose a matched job first.');return}if(!sourceText.trim()){setStatus('Add or paste your source resume text first.');return}setMode(nextMode);setBusy(true);setStatus(nextMode==='resume'?'Tailoring your resume…':'Drafting your cover letter…');const{data,error}=await supabase.functions.invoke('career-assistant',{body:{jobId:selectedJobId,mode:nextMode,sourceText,instructions}});if(error)setStatus(error.message);else{setOutput(String(data?.content??''));setGenerationMode(String(data?.generationMode??'structured'));setStatus(data?.generationMode==='openai'?'AI draft created. Review every claim before submitting.':'Structured draft created. Add an AI provider key later for model-generated rewriting.')}setBusy(false)}
  async function saveOutput(){if(!user||!selectedJobId||!output.trim())return;setBusy(true);const payload={user_id:user.id,job_id:selectedJobId,content:output.trim(),generation_mode:generationMode||'edited',updated_at:new Date().toISOString()};const table=mode==='resume'?'tailored_resumes':'cover_letters';const{error}=await supabase.from(table).upsert(mode==='resume'?{...payload,keywords:[],change_notes:['Edited and saved by user.']} : payload,{onConflict:'user_id,job_id'});setStatus(error?error.message:`${mode==='resume'?'Tailored resume':'Cover letter'} saved.`);setBusy(false)}
  function downloadText(){if(!output)return;const blob=new Blob([output],{type:'text/plain;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`${mode==='resume'?'tailored-resume':'cover-letter'}-${selectedJob?.company??'job'}.txt`.replace(/[^a-zA-Z0-9._-]/g,'-');a.click();URL.revokeObjectURL(url)}

  return <><header className="pageHeader"><div><p className="eyebrow">RESUME STUDIO</p><h1>Application documents, grounded in your real experience.</h1><p>Update your source CV, choose a matched role, then tailor a resume or draft a personalized cover letter. Generated text is always editable.</p></div></header>
  <div className="resumeStudioGrid"><section className="panel stack"><div className="sectionHeading"><div><p className="eyebrow">SOURCE FILE</p><h2>{resume?.original_filename||'No primary CV yet'}</h2></div><FilePenLine size={20}/></div><label>Replace CV or resume<input type="file" accept=".pdf,.docx,.txt" onChange={e=>setFile(e.target.files?.[0]??null)}/></label><button className="btn secondary" type="button" disabled={!file||busy} onClick={()=>void replaceResume()}><Upload size={15}/>Upload and replace</button><label>Source resume text<textarea rows={18} value={sourceText} onChange={e=>setSourceText(e.target.value)} placeholder="Your extracted CV text appears here. You can paste or correct it before tailoring."/></label><button className="btn secondary" type="button" disabled={!resume||busy} onClick={()=>void saveSource()}>Save source text</button><p className="finePrint">PDF, DOCX and TXT are parsed automatically when possible. Scanned PDFs may still need manual text correction.</p></section>
  <section className="panel stack assistantPanel"><div className="sectionHeading"><div><p className="eyebrow">CAREER ASSISTANT</p><h2>Tailor for a specific job</h2></div><Sparkles size={20}/></div><label>Matched job<select value={selectedJobId} onChange={e=>setSelectedJobId(e.target.value)}><option value="">Choose a role</option>{jobs.map(item=><option key={item.job_id} value={item.job_id}>{item.jobs?.title??'Job'} — {item.jobs?.company??'Company'} · {item.fit_score}% fit</option>)}</select></label><label>What should the assistant emphasize?<textarea rows={4} value={instructions} onChange={e=>setInstructions(e.target.value)} placeholder="Example: Keep it concise, foreground project coordination, use a confident professional tone."/></label><div className="assistantActions"><button className="btn primary" type="button" disabled={busy||!selectedJobId} onClick={()=>void generate('resume')}><Sparkles size={15}/>Tailor resume</button><button className="btn secondary" type="button" disabled={busy||!selectedJobId} onClick={()=>void generate('cover_letter')}>Draft cover letter</button></div>{selectedJob&&<div className="selectedJobCard"><b>{selectedJob.title}</b><span>{selectedJob.company}</span></div>}<div className="tabRow compact"><button type="button" className={mode==='resume'?'activeTab':''} onClick={()=>setMode('resume')}>Tailored resume</button><button type="button" className={mode==='cover_letter'?'activeTab':''} onClick={()=>setMode('cover_letter')}>Cover letter</button></div><label>{mode==='resume'?'Tailored resume draft':'Cover letter draft'}<textarea className="documentEditor" rows={22} value={output} onChange={e=>setOutput(e.target.value)} placeholder="Generate a draft, or write your own here."/></label><div className="assistantActions"><button className="btn secondary" type="button" disabled={!output||busy} onClick={()=>void saveOutput()}>Save changes</button><button className="btn secondary" type="button" disabled={!output} onClick={downloadText}><Download size={15}/>Download .txt</button></div>{generationMode&&<p className="finePrint">Generation mode: {generationMode==='openai'?'AI-assisted':'structured fallback'}. Always review before submission.</p>}</section></div>{status&&<p className="status" role="status">{status}</p>}</>}
