create table if not exists public.esco_term_cache (
  id bigint generated by default as identity primary key,
  term text not null,
  concept_type text not null check (concept_type in ('skill','occupation')),
  labels jsonb not null default '[]'::jsonb,
  fetched_at timestamptz not null default now(),
  unique(term, concept_type)
);

alter table public.esco_term_cache enable row level security;

comment on table public.esco_term_cache is
  'Server-side cache for free ESCO skill and occupation taxonomy lookups used by job matching.';
